import { Stage } from "./types";

export const colorPalette = [
  "#FF5733",
  "#3357FF",
  "#FF33A6",
  "#FF8C33",
  "#33FFEC",
  "#FF3380",
  "#33FF80",
  "#F3FF33",
  "#F833FF",
  "#33FF57",
  "#8C33FF",
  "#FF4D00",
  "#9DFF33",
  "#FF4500",
  "#F5FF33",
  "#A33FFF",
];

export const coreTechList = [
  "React",
  "Vue",
  "Angular",
  "Laravel",
  "Django",
  "Python",
  "Node.js",
  "Express",
  "Java",
  "Spring",
  "Ruby on Rails",
  "PHP",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "C++",
  "C#",
  "TypeScript",
  "JavaScript",
  "HTML5",
  "CSS3",
  "SASS",
  "Tailwind CSS",
  "Bootstrap",
  "JQuery",
  "GraphQL",
  "Apollo",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Firebase",
  "AWS",
  "Google Cloud",
  "Azure",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Jenkins",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Terraform",
  "Ansible",
  "Nginx",
  "Apache",
  "Vercel",
  "Netlify",
  "Heroku",
  "Rails",
  "Next.js",
  "Gatsby",
  "Nuxt.js",
  "Flutter",
  "React Native",
  "Electron",
  "Elixir",
  "Scala",
  "Haskell",
  "Figma",
  "Sketch",
  "Adobe XD",
  "InVision",
  "Zeplin",
  "Jira",
  "Trello",
  "Notion",
  "Slack",
  "Discord",
  "Zoom",
  "Stripe",
  "PayPal",
  "MongoDB Atlas",
  "ElasticSearch",
  "Redis",
  "SQLite",
  "Salesforce",
  "Shopify",
  "Magento",
  "WordPress",
  "BigCommerce",
  "Wix",
  "Squarespace",
];

export const flowTemplates: Record<string, Stage[]> = {
  "Basic CI Flow": [
    { name: "Local", label: "Environment", color: "#FF5733", stageNumber: 1 },
    { name: "Raise PR", label: "Manual", color: "#F5FF33", stageNumber: 2 },
    { name: "CI/CD", label: "Automation", color: "#9DFF33", stageNumber: 3 },
    {
      name: "Review PR",
      label: "Automation",
      color: "#9DFF33",
      stageNumber: 4,
    },
    { name: "Merge PR", label: "Manual", color: "#F5FF33", stageNumber: 5 },
    { name: "Deploy", label: "Automation", color: "#9DFF33", stageNumber: 6 },
  ],
  "Review Flow": [
    { name: "Raise PR", label: "Manual", color: "#F5FF33", stageNumber: 1 },
    { name: "Review PR", label: "Manual", color: "#F5FF33", stageNumber: 2 },
    { name: "Chromatic", label: "Manual", color: "#F5FF33", stageNumber: 3 },
    { name: "CI", label: "Automation", color: "#9DFF33", stageNumber: 3 },
    { name: "Merge PR", label: "Manual", color: "#F5FF33", stageNumber: 4 },
  ],
};
